### ISSUE TITLE
Parse error on xlink:href attribute

### ISSUE THREAD

**Issue by jenssegers** [kolint/kolint#203]
**Current behavior**
Parsing fails for files containing `<use xlink:href="#slack-tile">`

**Expected behavior**
Parsing works.

**Steps to reproduce**
Run linting for a file containing `<use xlink:href="#slack-tile">`

**Comment by tscpp** [comment]
Thank you for your bug report! We're currently working on fixing it.

**Comment by tscpp** [comment]
Release [0.0.4](https://www.npmjs.com/package/knockout-lint) has been published with the fix (#204) for the bug

**Comment by tscpp** [comment]
Release [0.0.4](https://www.npmjs.com/package/knockout-lint) may have breaking changes to prior versions. We're sorry for the inconvenience
