### ISSUE TITLE
Relax type for the "text" binding.

### ISSUE THREAD

**Issue by maskmaster** [kolint/kolint#320]
```html
<!-- ko-import viewmodel from './viewmodel' -->
<!-- ko-viewmodel viewmodel -->
<title data-bind="text: title"></title>
```
```typescript
import * as ko from 'knockout'
export default class ViewModel {
	public title = ko.observable(1)
}
```
The example above is currently giving an error about title not being a string.

Since it is such a common thing to display numerical values, it gets a bit counter-productive to call ".toString()" in all such text-bindings. An alternative approach is to utilize a "numerical" binding that does what "text" is doing (and possibly handles different kinds of numerical formattings). However, there is no such standard binding-handler in knockout.

The suggested way forward is to relax the type strictness to also allow numbers for the text-bindings.

**Comment by tscpp** [comment]
Don't know if I agree. In my opinion, the types should be strict and not allow implicit type conversion. Only if a binding does _explicit_ type conversion, other or unknown types should be allowed. This is especially dangerous in cases where the type can be undefined, then "undefined" will be displayed, without any linting errors/warnings.

**Comment by maskmaster** [comment]
Making it optional means that we need to identify this specific case and then to be able to set that in the configuration. We have no such capabilities today and it will probably require a pretty big effort to implement. I suggest that we create an issue for it and plan it for the future. In the meantime it should not be necessary to write `data-bind = "text: mynumber.toString()"` whenever we want to output a numerical value.
