### ISSUE TITLE
Should kolint run the project's TypeScript version?

### ISSUE THREAD

**Issue by tscpp** [kolint/kolint#323]
Currently, kolint runs our TypeScript version. This can cause errors both in the generated file and the config file if the TypeScript versions don't match. Should not TypeScript be a [peer dependency](https://nodejs.org/es/blog/npm/peer-dependencies/)? The problem when using it as a peer dependency is that if the peer dependency doesn't match, there will be a conflict and kolint might not run cause TypeScript is outdated.

**Comment by ondrejmirtes** [comment]
I'd very much appreciate if kolint used the same TS version the project uses.

A sample problem I have right now is that KOLint's TS version doesn't know `es2023` lib (set in my tsconfig.json), so it complains that `toSorted` does not exist on Array.prototype.

**Comment by ondrejmirtes** [comment]
An idea - there could be some underlying kolint command users could call, to just compile the templates into .ts files. The user could then call `tsc` on these compiled .ts files themselves however they wanted.

**Comment by tscpp** [comment]
> An idea - there could be some underlying kolint command users could call, to just compile the templates into .ts files. The user could then call `tsc` on these compiled .ts files themselves however they wanted.

You can already do that with the `--out` flag. However, tsc will not report the kolint rules, only type issues.

Unfortunately, the compiler still needs the tsconfig to build the ts file (the ts compiler host requires compiler options defined in tsconfig) anyways.

**Comment by tscpp** [comment]
Fixed in [kolint/next](https://github.com/kolint/next/) (unreleased)
