### ISSUE TITLE
Allow specifying path to tsconfig.json

### ISSUE THREAD

**Issue by ondrejmirtes** [kolint/kolint#333]
Right now kolint looks for tsconfig.json in the current working directory, right? It'd be cool to allow specifying a different tsconfig.json file path. Perhaps I'd want to check KO templates with a different strictness.

Related: https://github.com/kolint/kolint/issues/323

**Comment by tscpp** [comment]
Fixed in [kolint/next](https://github.com/kolint/next/) (unreleased)
