### ISSUE TITLE
Bug - severity config broken

### ISSUE THREAD

**Issue by ondrejmirtes** [kolint/kolint#337]
Right now severity from config is handled with these lines of code:

https://github.com/kolint/kolint/blob/b813781362a6f75af8d013634fc33c12a5c5c234/src/cli/index.ts#L178-L205

When I give KOLint this config file:

```
module.exports = {
	severity: {
		'TS6133': 'off',
		'TS7006': 'off',
		'TS7016': 'off',
		'TS6198': 'off',
	},
	root: true,
}
```

It will produce two problems:

1) All error codes not mentioned by the config file will have `diag.severity` `undefined` as a result of this line:

```
const severity = config.severity[diag.code] ?? config.severity[diag.name]
```

2) KOLint will always produce exit code zero and report 0 problems because none of these conditions will match:

```
			if (diag.severity === kolint.Severity.Error)
				errors++
			if (diag.severity === kolint.Severity.Warning)
				warnings++
```

**Comment by tscpp** [comment]
Fixed in [kolint/next](https://github.com/kolint/next/) (unreleased)
