### ISSUE TITLE
Config/annotation to ignore paths

### ISSUE THREAD

**Issue by ondrejmirtes** [kolint/kolint#340]
Let's say we want to lint `frontend/**/*.html` but some of the `.html` files in there are not actually for Knockout viewmodels. Right now KOLint will complain:

```
warning KO0002 Missing Viewmodel reference
```

It would be great if we could exclude from the includelist. Or maybe there could be an annotation like "Ignore this specific error code in this file".

**Comment by tscpp** [comment]
Fixed in [kolint/next](https://github.com/kolint/next/) (unreleased)
