### ISSUE TITLE
Hide unavailable names in generated file

### ISSUE THREAD

**Issue by tscpp** [kolint/kolint#37]
**Current behavior**
All variables and functions in the generated TypeScript file will be fully available to the user.

**Expected behavior**
All variables and functions should be hidden from the user using a namespace or object.

```typescript
let _ko = {}

...

_ko.binding_1 = function () {
   _ko = undefined

   ...
}

```

**Comment by maskmaster** [comment]
Will not be done in the forseeable future. Closing.
