### ISSUE TITLE
Output source locations in generated file

### ISSUE THREAD

**Issue by maskmaster** [kolint/kolint#77]
**Current behavior**
The generated code is a bit hard to map to the original view unless mapping with the sourcemap.

**Expected behavior**
The generated code should optionally include references to line+row in the original view to ease debugging of the generated code.

**Comment by tscpp** [comment]
How should we include the references in the view file? By comments?

**Comment by maskmaster** [comment]
This is unfeasible since it is common that identifiers on the same row are mapped back to multiple different places. The source maps provice the mapping functionality for now.
